# Configure regular AutoRecon options at the top of this file.

# nmap-append = '-T3'
# verbose = 1
# max-scans = 30
max-scans = 5

# Configure global options here.
[global]
password-wordlist = '/usr/share/seclists/Passwords/2023-200_most_used_passwords.txt'
# username-wordlist = '/usr/share/seclists/Usernames/cirt-default-usernames.txt'

# Configure plugin options here.
[dirbuster]
tool = 'gobuster'
ext = 'txt,html,php,jsp,pdf'
wordlist = [
 	'/usr/share/wordlists/dirb/common.txt',
 	'/usr/share/wordlists/dirb/big.txt',
 	'/usr/share/wordlists/dirbuster/directory-list-2.3-small.txt',
    '/usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt'
]
